### PR TITLE
Fix epsilon handling.

### PR DESCRIPTION
**Pull request by gw0**

### CODE REVIEW

**Comment by EderSantana** [comment]
Thanks for the PR
I didn't setup a CI yet.  Did the experiments run fine?

**Comment by EderSantana** [comment]
Hi, I merged your other PR and it conflicts with this one. could you please check it out and update it?

**Comment by gw0** [comment]
Ok, I see that @mattsqerror already prepared and improved this.

**Comment by EderSantana** [comment]
yeah thanks for pointing that out

**Pull request closed without merging**
